patch functio

diff --git a/linux-2/PKGBUILD b/linux-2/PKGBUILD
--- a/linux-2/PKGBUILD
+++ b/linux-2/PKGBUILD
@@ -113,6 +113,27 @@ export KBUILD_BUILD_HOST=${KBUILD_BUILD_HOST:-archlinux}
 export KBUILD_BUILD_USER=${KBUILD_BUILD_USER:-makepkg}
 export KBUILD_BUILD_TIMESTAMP=${KBUILD_BUILD_TIMESTAMP:-$(date -Ru${SOURCE_DATE_EPOCH:+d @$SOURCE_DATE_EPOCH})}
 
+_patch() {
+    output=$(patch -Np1 -F3 --input="../${1}" -r - 2>&1)
+    exit_code=$?
+    checker=$(echo $output | grep  "Skipping patch")
+
+    # Jika patch gagal (exit code bukan 0), kembalikan exit code tetapi tidak exit dari script
+    if [ $exit_code -ne 0 ]; then
+        if [ -n "$checker" ]; then 
+          echo $output
+          return 0
+        fi
+
+        echo "Patch command failed with exit code $exit_code"
+        return $exit_code
+    fi
+
+    echo $output
+    return 0
+}
+
+
 prepare() {
   cd linux-${_major}
 
@@ -130,7 +151,7 @@ prepare() {
     src="${src##*/}"
     [[ $src = *.patch ]] || continue
     msg2 "Applying patch $src..."
-    patch -Np1 -F3 --input="../$src" -r -
+    _patch $src
     # OUT="$(patch -Np1 -F2 --input="../$src" -r -)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false);
   done
 
