remove lto

diff --git a/llvm-essential/PKGBUILD b/llvm-essential/PKGBUILD
--- a/llvm-essential/PKGBUILD
+++ b/llvm-essential/PKGBUILD
@@ -1,5 +1,5 @@
-pkgname=llvm-bootstrap
-pkgdesc="LLVM Toolchain with clang, clang-tools-extra, openmp, compiler-rt, polly, lldb, lld"
+pkgname=llvm-all
+pkgdesc="LLVM Toolchain with clang, clang-tools-extra, compiler-rt, polly, lldb, lld"
 pkgver=18.1.8
 pkgrel=4
 arch=('x86_64')
@@ -7,30 +7,29 @@ url="https://llvm.org/"
 license=('custom:Apache 2.0 with LLVM Exception')
 
 provides=('llvm' "llvm=${pkgver}" 'llvm-libs' 'llvm-ocaml' 'clang' "clang=${pkgver}"
-  'clang-analyzer' 'clang-tools-extra' 'polly' 'openmp'
-  'lld')
+  'clang-analyzer' 'clang-tools-extra' 'polly' 'compiler-rt' 'openmp' 'libunwind'
+  'lld' 'lldb' 'libc++' 'libc++abi' 'libc++experimental')
 
 replaces=('llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
-  'clang-tools-extra' 'polly' 'openmp' 'lld'
-)
+  'clang-tools-extra' 'polly' 'compiler-rt' 'lld' 'lldb' 'openmp'
+  'libc++' 'libc++abi' 'libc++experimental' 'libunwind')
 
 conflicts=('llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
-  'clang-tools-extra' 'polly' 'openmp' 'lld'
-  'llvm-git' 'llvm-libs-git' 'llvm-ocaml-git'
-)
+  'clang-tools-extra' 'polly' 'compiler-rt' 'lld' 'lldb' 'openmp'
+  'llvm-git' 'llvm-libs-git' 'llvm-ocaml-git' 'libc++' 'libunwind'
+  'libc++abi' 'libc++experimental')
 
-depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses' 'compiler-rt' 'gcc-libs')
+depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses' 'xz' 'zlib')
 _ocaml_ver=4.14.0
 makedepends=(
-  'git' 'ninja' 'cmake' 'llvm' 'clang'
+  'git' 'ninja' 'cmake'
   "ocaml>=${_ocaml_ver}" 'ocaml-ctypes' 'ocaml-findlib'
   'python-setuptools' 'python-psutil' 'python-sphinx'
   'python-recommonmark' 'ocaml-stdlib-shims' 'mimalloc'
 )
 makedepends_x86_64=('lib32-gcc-libs')
-_commit=8dfdcc7b7bf66834a761bd8de445840ef68e4d1a
 source=(
-  "https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${pkgver}.zip"
+  "https://github.com/llvm/llvm-project/releases/download/llvmorg-${pkgver}/llvm-project-${pkgver}.src.tar.xz"
   'llvm-config.h'
 )
 
@@ -39,17 +38,17 @@ sha256sums=('SKIP'
 
 options=('staticlibs' '!lto' '!debug')
 
-_skip_build_test=n
+_skip_build_test=y
 _skip_documentation=y
 _extra_build_flags=(
-  -DCMAKE_EXE_LINKER_FLAGS=-Wl,--push-state,/usr/lib/libmimalloc.a,--pop-state 
-  -DCMAKE_CXX_STANDARD=17
+  -DLLVM_ENABLE_LTO=Thin 
+  -DCMAKE_EXE_LINKER_FLAGS=-Wl,--push-state,/usr/lib/libmimalloc.a,--pop-state -DCMAKE_CXX_STANDARD=17
   -DCMAKE_SKIP_RPATH=ON
   -DENABLE_LINKER_BUILD_ID=ON
-)
+  )
 _build_documentation=0
 _build_tests=0
-_build_bindings=1
+_build_bindings=0
 
 _rpatch() {
 
@@ -67,7 +66,10 @@ _patch() {
 
 prepare() {
 
-  mv llvm-project-llvmorg-${pkgver} llvm-project
+  mv "${srcdir:?}/llvm-project-${pkgver}.src" llvm-project || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
+    exit 1
+  )
 
   cd "${srcdir:?}/llvm-project" || (
     echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
@@ -87,19 +89,23 @@ build() {
     exit 1
   )
 
-  _extra_build_flags+=()
-
+  _extra_build_flags+=(
+    -DCMAKE_C_COMPILER="$CC"
+    -DCMAKE_CXX_COMPILER="$CXX"
+  )
 
   export CFLAGS="$CFLAGS -fno-plt -fomit-frame-pointer -fno-semantic-interposition"
   export CXXFLAGS="$CXXFLAGS -fno-plt -fomit-frame-pointer -fno-semantic-interposition"
+  export LDFLAGS="$LDFLAGS -Wl,-Bsymbolic-functions"
 
-  # if ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
-  #   export LD=ld.lld
-  #   export CC_LD=lld
-  #   export CXX_LD=lld
-  #   export HOSTLD=ld.lld
-  #   _extra_build_flags+=(-DLLVM_USE_LINKER=lld)
-  # fi
+
+  if ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+    export LD=ld.lld
+    export CC_LD=lld
+    export CXX_LD=lld
+    export HOSTLD=ld.lld
+    _extra_build_flags+=(-DLLVM_USE_LINKER=lld)
+  fi
 
   while true; do
     case ${_skip_build_test} in
@@ -138,27 +144,26 @@ build() {
     esac
   done
 
-
-  echo "CFLAGS $CFLAGS"
-  echo "CXXFLAGS $CXXFLAGS"
-  echo "LDFLAGS $LDFLAGS"
-
   cmake -S llvm -B build -G Ninja \
     -DCMAKE_BUILD_TYPE=Release \
     -DCMAKE_INSTALL_PREFIX=/usr \
     -DLLVM_BINUTILS_INCDIR=/usr/include \
     -DLLVM_BUILD_RUNTIME=ON \
     -DLLVM_HOST_TRIPLE="${CHOST:?}" \
+    -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON \
     -DLLVM_BUILD_LLVM_DYLIB=ON \
     -DLLVM_LINK_LLVM_DYLIB=ON \
+    -DCLANG_LINK_CLANG_DYLIB=ON \
     -DLLVM_INSTALL_UTILS=ON \
     -DLLVM_ENABLE_RTTI=ON \
     -DLLVM_ENABLE_FFI=ON \
-    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;openmp;polly" \
+    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;lld;lldb;mlir;polly;pstl" \
+    -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;openmp;libunwind" \
     -DCLANG_LINK_CLANG_DYLIB=ON \
+    -DLLDB_USE_SYSTEM_SIX=1 \
     -DLIBOMP_INSTALL_ALIASES=OFF \
     -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
-    -DPOLLY_ENABLE_GPGPU_CODEGEN=OFF \
+    -DPOLLY_ENABLE_GPGPU_CODEGEN=ON \
     -DCLANG_DEFAULT_PIE_ON_LINUX=ON \
     "${_extra_build_flags[@]}"
 
@@ -167,7 +172,6 @@ build() {
   if [[ _build_documentation -eq 1 && _build_bindings -ne 0 ]]; then
     ninja -C build ocaml_doc
   fi
-
 
 }
 
@@ -182,7 +186,9 @@ check() {
     ninja -C build check-llvm
     ninja -C build check-clang
     ninja -C build check-clang-tools
+    ninja -C build check-openmp
     ninja -C build check-polly
+    ninja -C build check-lldb
     ninja -C build check-lld
   fi
 
@@ -233,11 +239,11 @@ package() {
   ln -s x86_64-pc-linux-gnu/* .
   popd
 
-
   # Clang
   site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
   install -d "${pkgdir:?}/${site_packages}"
   mv "${pkgdir:?}/usr/lib/"{libear,libscanbuild} "${pkgdir:?}/${site_packages}/"
+  cp -a clang/bindings/python/clang "${pkgdir:?}/${site_packages}/"
 
   mv "${pkgdir:?}"/usr/libexec/* "${pkgdir:?}/usr/lib/clang/"
   rm -fr "${pkgdir:?}/usr/libexec"
@@ -256,12 +262,14 @@ package() {
   install -Dm644 "${srcdir:?}/llvm-project/llvm/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/llvm-LICENSE"
   install -Dm644 "${srcdir:?}/llvm-project/clang/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-LICENSE"
   install -Dm644 "${srcdir:?}/llvm-project/clang-tools-extra/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-tools-extra-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/compiler-rt/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/compiler-rt-LICENSE"
   install -Dm644 "${srcdir:?}/llvm-project/lld/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lld-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/lldb/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lldb-LICENSE"
   install -Dm644 "${srcdir:?}/llvm-project/polly/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/polly-LICENSE"
   install -Dm644 "${srcdir:?}/llvm-project/openmp/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/openmp-LICENSE"
 
   # Fallback for llvm 16
-  # _llvm_libs=(libLLVM-16.so libLTO.so.16 libRemarks.so.16 libclang.so.16.0.6 libclang-cpp.so.16)
+  # _llvm_libs=(libLLVM-16.so libLTO.so.16 libRemarks.so.16 libclang.so.16.0.6 liblldb.so.16.0.6 libclang-cpp.so.16)
   # for lib in "${_llvm_libs[@]}"; do
   #   if [[ ! -e "${pkgdir:?}/usr/lib/${lib:?}" ]]; then
   #     echo "- Copy ${lib:?}"
