ss

diff --git a/llvm-runtime/PKGBUILD b/llvm-runtime/PKGBUILD
--- a/llvm-runtime/PKGBUILD
+++ b/llvm-runtime/PKGBUILD
@@ -1,93 +1,273 @@
-# Maintainer: Evangelos Foutras <evangelos@foutrelis.com>
-# Contributor: Jan "heftig" Steffens <jan.steffens@gmail.com>
-
-pkgname=llvm
-pkgver=14.0.1
+pkgname=llvm-all
+pkgdesc="LLVM Toolchain with clang, clang-tools-extra, compiler-rt, openmp, polly, lldb, lld"
+pkgver=14.0.6
 pkgrel=1
-_ocaml_ver=4.13.1
 arch=('x86_64')
 url="https://llvm.org/"
-provides=('llvm' "llvm=${pkgver}" 'llvm-libs' 'llvm-ocaml')
+license=('custom:Apache 2.0 with LLVM Exception')
 
-replaces=('llvm' 'llvm-libs' 'llvm-ocaml')
+provides=('llvm' "llvm=${pkgver}" 'llvm-libs' 'llvm-ocaml' 'clang' "clang=${pkgver}"
+  'clang=13.0.1' 'clang-analyzer' 'clang-tools-extra' 'openmp' 'polly' 'compiler-rt'
+  'lld' 'lldb' 'libc++' 'libc++abi' 'libc++experimental')
 
-conflicts=('llvm' 'llvm-libs' 'llvm-ocaml'
-  'llvm-git' 'llvm-libs-git' 'llvm-ocaml-git')
+replaces=('llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
+  'clang-tools-extra' 'openmp' 'polly' 'compiler-rt' 'lld' 'lldb'
+  'libc++' 'libc++abi' 'libc++experimental')
+
+conflicts=('llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
+  'clang-tools-extra' 'openmp' 'polly' 'compiler-rt' 'lld' 'lldb'
+  'llvm-git' 'llvm-libs-git' 'llvm-ocaml-git' 'libc++'
+  'libc++abi' 'libc++experimental')
 
 depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses')
-license=('custom:Apache 2.0 with LLVM Exception')
-makedepends=('cmake' 'ninja' 'libffi' 'libedit' 'ncurses' 'libxml2'
-             "ocaml>=$_ocaml_ver" 'ocaml-ctypes' 'ocaml-findlib'
-             'python-setuptools' 'python-psutil' 'python-sphinx'
-             'python-recommonmark')
-_source_base=https://github.com/llvm/llvm-project/releases/download/llvmorg-$pkgver
-source=($_source_base/$pkgname-$pkgver.src.tar.xz{,.sig}
-        llvm-config.h)
+_ocaml_ver=4.13.1
+makedepends=(
+  'git' 'ninja' 'cmake'
+  "ocaml>=${_ocaml_ver}" 'ocaml-ctypes' 'ocaml-findlib'
+  'python-setuptools' 'python-psutil' 'python-sphinx'
+  'python-recommonmark'
+)
+makedepends_x86_64=('lib32-gcc-libs')
+_commit=f28c006a5895fc0e329fe15fead81e37457cb1d1
+source=(
+  "llvm-project::git+https://github.com/llvm/llvm-project.git#commit=${_commit}"
+  'llvm-config.h'
+)
+
 sha256sums=('SKIP'
-            'SKIP'
-            'SKIP'
-            )
-validpgpkeys+=('B6C8F98282B944E3B0D5C2530FC3042E345AD05D') # Hans Wennborg <hans@chromium.org>
-validpgpkeys+=('474E22316ABF4785A88C6E8EA2C794A986419D8A') # Tom Stellard <tstellar@redhat.com>
+  '597dc5968c695bbdbb0eac9e8eb5117fcd2773bc91edf5ec103ecffffab8bc48')
+
+options=('staticlibs')
+
+_skip_build_test=y
+_skip_documentation=y
+_extra_build_flags=(-DLLVM_ENABLE_LTO=Thin)
+_build_documentation=0
+_build_tests=0
+_build_bindings=0
+
+_rpatch() {
+
+  echo -e "\E[1;33m Revert patch: ${1}\E[0m"
+  patch --forward --reverse --strip=1 --input="${srcdir:?}/${1}"
+
+}
+
+_patch() {
+
+  echo -e "\E[1;33m Apply patch: ${1}\E[0m"
+  patch --forward --strip=1 --input="${srcdir:?}/${1}"
+
+}
 
 prepare() {
-  cd "$srcdir/llvm-$pkgver.src"
-  mkdir build
+
+  cd "${srcdir:?}/llvm-project" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
+    exit 1
+  )
+
+  # Attempt to convert script to Python 3
+  2to3 -wn --no-diffs \
+    clang-tools-extra/clang-include-fixer/find-all-symbols/tool/run-find-all-symbols.py
+
 }
 
 build() {
-  cd "$srcdir/llvm-$pkgver.src/build"
 
-  cmake .. -G Ninja \
-    -DCMAKE_C_COMPILER=clang \
-    -DCMAKE_CXX_COMPILER=clang++ \
+  cd "${srcdir:?}/llvm-project" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Build Failed! \E[0m"
+    exit 1
+  )
+
+  if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]"; then
+    export DEBUG_CFLAGS="-g"
+    export DEBUG_CXXFLAGS="-g"
+    _extra_build_flags+=(
+      -DCMAKE_C_COMPILER=clang
+      -DCMAKE_CXX_COMPILER=clang++
+    )
+  else
+    echo -e "\E[1;31mClang not found. Will use default system compiler! \E[0m"
+  fi
+
+  if ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+    _extra_build_flags+=(-DLLVM_USE_LINKER=lld)
+  fi
+
+  while true; do
+    case ${_skip_build_test} in
+    [Yy] | "")
+      _build_tests=0
+      _extra_build_flags+=(-DLLVM_BUILD_TESTS=OFF)
+      break
+      ;;
+    [Nn])
+      _build_tests=1
+      _extra_build_flags+=(-DLLVM_BUILD_TESTS=ON)
+      break
+      ;;
+    *) echo -e "\E[1;31mPlease answer Y or N! \E[0m" ;;
+    esac
+  done
+
+  while true; do
+    case ${_skip_documentation} in
+    [Yy] | "")
+      _build_documentation=0
+      _extra_build_flags+=(-DLLVM_BUILD_DOCS=OFF)
+      break
+      ;;
+    [Nn])
+      _build_documentation=1
+      _extra_build_flags+=(
+        -DLLVM_BUILD_DOCS=ON
+        -DLLVM_ENABLE_SPHINX=ON
+        -DLLVM_ENABLE_DOXYGEN=OFF
+        -DSPHINX_WARNINGS_AS_ERRORS=OFF
+      )
+      break
+      ;;
+    *) echo -e "\E[1;31mPlease answer Y or N! \E[0m" ;;
+    esac
+  done
+
+  cmake -S llvm -B build -G Ninja \
     -DCMAKE_BUILD_TYPE=Release \
     -DCMAKE_INSTALL_PREFIX=/usr \
-    -DCMAKE_SKIP_RPATH=ON \
-    -DLLVM_HOST_TRIPLE=$CHOST \
+    -DLLVM_BINUTILS_INCDIR=/usr/include \
+    -DLLVM_HOST_TRIPLE="${CHOST:?}" \
+    -DLLVM_BUILD_RUNTIME=ON \
+    -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON \
     -DLLVM_BUILD_LLVM_DYLIB=ON \
     -DLLVM_LINK_LLVM_DYLIB=ON \
+    -DCLANG_LINK_CLANG_DYLIB=ON \
     -DLLVM_INSTALL_UTILS=ON \
     -DLLVM_ENABLE_RTTI=ON \
     -DLLVM_ENABLE_FFI=ON \
-    -DLLVM_BUILD_TESTS=OFF \
-    -DLLVM_BUILD_DOCS=ON \
-    -DLLVM_BINUTILS_INCDIR=/usr/include \
-    -DLLVM_ENABLE_LTO=Thin -DLLVM_USE_LINKER=lld
-  ninja all ocaml_doc
+    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;lld;lldb;mlir;openmp;polly;pstl" \
+    -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
+    -DCLANG_LINK_CLANG_DYLIB=ON \
+    -DLLDB_USE_SYSTEM_SIX=1 \
+    -DLIBOMP_INSTALL_ALIASES=OFF \
+    -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
+    -DPOLLY_ENABLE_GPGPU_CODEGEN=ON \
+    -DCLANG_DEFAULT_PIE_ON_LINUX=ON \
+    "${_extra_build_flags[@]}"
+
+  ninja -C build
+
+  if [[ _build_documentation -eq 1 && _build_bindings -ne 0 ]]; then
+    ninja -C build ocaml_doc
+  fi
+
 }
 
 check() {
-  cd "$srcdir/llvm-$pkgver.src/build"
-  LD_LIBRARY_PATH=$PWD/lib ninja check
-}
 
-package_llvm() {
-  pkgdesc="Collection of modular and reusable compiler and toolchain technologies"
+  cd "${srcdir:?}/llvm-project" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project/build directory! Check Failed! \E[0m"
+    exit 1
+  )
 
-  cd "$srcdir/llvm-$pkgver.src/build"
-
-  DESTDIR="$pkgdir" ninja install
-
-  # Include lit for running lit-based tests in other projects
-  pushd ../utils/lit
-  python3 setup.py install --root="$pkgdir" -O1
-  popd
-
-  # Remove documentation sources
-  rm -r "$pkgdir"/usr/share/doc/$pkgname/html/{_sources,.buildinfo}
-
-  # The runtime libraries go into llvm-libs
-  install -d "$pkgdir/usr/lib/bfd-plugins"
-  ln -s ../LLVMgold.so "$pkgdir/usr/lib/bfd-plugins/LLVMgold.so"
-
-  if [[ $CARCH == x86_64 ]]; then
-    # Needed for multilib (https://bugs.archlinux.org/task/29951)
-    # Header stub is taken from Fedora
-    mv "$pkgdir/usr/include/llvm/Config/llvm-config"{,-64}.h
-    cp "$srcdir/llvm-config.h" "$pkgdir/usr/include/llvm/Config/llvm-config.h"
+  if [[ _build_tests -eq 1 ]]; then
+    ninja -C build check-llvm
+    ninja -C build check-clang
+    ninja -C build check-clang-tools
+    ninja -C build check-openmp
+    ninja -C build check-polly
+    ninja -C build check-lldb
+    ninja -C build check-lld
   fi
 
-  install -Dm644 ../LICENSE.TXT "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
 }
-# vim:set ts=2 sw=2 et:
+
+_python_optimize() {
+  python -m compileall "$@"
+  python -O -m compileall "$@"
+  python -OO -m compileall "$@"
+}
+
+package() {
+
+  cd "${srcdir:?}/llvm-project" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Package Failed! \E[0m"
+    exit 1
+  )
+
+  if [[ _build_documentation -eq 0 ]]; then
+    mkdir -p "${srcdir:?}/llvm-project/build/docs/ocamldoc/html/"
+  fi
+
+  DESTDIR="${pkgdir:?}" ninja -C build install
+
+  pushd llvm/utils/lit || (
+    echo -e "\E[1;31mpushd utils/lit - Package Failed! \E[0m"
+    exit 1
+  )
+
+  python setup.py install --root="${pkgdir:?}" -O1
+  popd || (
+    echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+    exit 1
+  )
+
+  if [[ "${CARCH:?}" == "x86_64" ]]; then
+    mv "${pkgdir:?}/usr/include/llvm/Config/llvm-config"{,-64}.h
+    cp "${srcdir:?}/llvm-config.h" "${pkgdir:?}/usr/include/llvm/Config/llvm-config.h"
+  fi
+
+  # Symlink LLVMgold.so from /usr/lib/bfd-plugins
+  # https://bugs.archlinux.org/task/28479
+  mkdir -p "${pkgdir:?}/usr/lib/bfd-plugins"
+  ln -s ../LLVMgold.so "${pkgdir:?}/usr/lib/bfd-plugins/LLVMgold.so"
+
+  # Clang
+  site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
+  install -d "${pkgdir:?}/${site_packages}"
+  mv "${pkgdir:?}/usr/lib/"{libear,libscanbuild} "${pkgdir:?}/${site_packages}/"
+  cp -a llvm/bindings/python/llvm "${pkgdir:?}/${site_packages}/"
+  cp -a clang/bindings/python/clang "${pkgdir:?}/${site_packages}/"
+
+  mv "${pkgdir:?}"/usr/libexec/* "${pkgdir:?}/usr/lib/clang/"
+  rm -fr "${pkgdir:?}/usr/libexec"
+  sed -i 's|libexec|lib/clang|' \
+    "${pkgdir:?}/usr/bin/scan-build" \
+    "${pkgdir:?}/${site_packages}/libscanbuild/analyze.py"
+
+  _python_optimize "${pkgdir:?}/usr/share" "${pkgdir:?}/${site_packages}"
+
+  # Remove html documentation
+  if [[ _build_documentation -eq 0 ]]; then
+    rm -fr "${pkgdir:?}/usr/share/doc"
+  fi
+
+  # Licenses
+  install -Dm644 "${srcdir:?}/llvm-project/llvm/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/llvm-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/clang/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/clang-tools-extra/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-tools-extra-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/compiler-rt/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/compiler-rt-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/lld/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lld-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/lldb/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lldb-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/polly/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/polly-LICENSE"
+  install -Dm644 "${srcdir:?}/llvm-project/openmp/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/openmp-LICENSE"
+
+  # Fallback for llvm 13
+  _llvm_libs=(libLLVM-13.so libLTO.so.13 libRemarks.so.13 libclang.so.13.0.1 libclang-cpp.so.13)
+  for lib in "${_llvm_libs[@]}"; do
+    if [[ ! -e "${pkgdir:?}/usr/lib/${lib:?}" ]]; then
+      echo "- Copy ${lib:?}"
+      install -Dm644 "/usr/lib/${lib:?}" "${pkgdir:?}/usr/lib/${lib:?}"
+    else
+      echo "- ${lib:?} exist"
+    fi
+  done
+
+  if [[ ! -e "${pkgdir:?}/usr/lib/libLLVM-13.0.1.so" ]]; then
+    echo "- Copy libLLVM-13.0.1.so"
+    ln -s /usr/lib/libLLVM-13.so "${pkgdir:?}/usr/lib/libLLVM-13.0.1.so"
+  else
+    echo "- libLLVM-13.0.1.so exist"
+  fi
+
+}
