s

diff --git a/python/PKGBUILD b/python/PKGBUILD
--- a/python/PKGBUILD
+++ b/python/PKGBUILD
@@ -1,9 +1,7 @@
-
-
 shopt -s extglob
 
-pkgbase=python
-pkgname=(python python-tests)
+pkgbase=python+clang
+pkgname=(python+clang python-tests+clang)
 pkgver=3.10.5
 pkgrel=1
 _pybasever=${pkgver%.*}
@@ -48,51 +46,127 @@ prepare() {
 
 }
 
-
 build() {
-  cd "${srcdir}/Python-${pkgver}"
 
-  CFLAGS="${CFLAGS/-O2/-O3} -fno-semantic-interposition"
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Build Failed! \E[0m"
+    exit 1
+  )
 
+  if [[ ${_llvm} -eq 1 ]]; then
+
+    LDFLAGS="${LDFLAGS} -fuse-ld=lld"
+
+  fi
+
+  # Disable bundled pip & setuptools
   ./configure --prefix=/usr \
-              --enable-shared \
-              --with-threads \
-              --with-lto \
-              --enable-optimizations \
-              --with-computed-gotos \
-              --enable-ipv6 \
-              --with-system-expat \
-              --with-dbmliborder=gdbm:ndbm \
-              --with-system-libmpdec \
-              --enable-loadable-sqlite-extensions \
-              --without-ensurepip
+    --enable-shared \
+    --enable-ipv6 \
+    --enable-loadable-sqlite-extensions \
+    --enable-optimizations \
+    --with-lto \
+    --with-computed-gotos \
+    --with-system-expat \
+    --with-dbmliborder=gdbm:ndbm \
+    --with-system-ffi \
+    --with-system-libmpdec \
+    --without-ensurepip \
+    --with-tzpath=/usr/share/zoneinfo
+
   unset CFLAGS
   unset CXXFLAGS
   unset LDFLAGS
+
   LC_CTYPE=en_US.UTF-8 make regen-all EXTRA_CFLAGS="${CFLAGS}"
   LC_CTYPE=en_US.UTF-8 make EXTRA_CFLAGS="${CFLAGS}"
+
 }
 
-package() {
-  cd "${srcdir}/Python-${pkgver}"
-  # altinstall: /usr/bin/pythonX.Y but not /usr/bin/python or /usr/bin/pythonX
-  make DESTDIR="${pkgdir}" altinstall maninstall
+check() {
+
+  # test_socket: test.test_socket.RDSTest.testPeek hangs https://bugs.python.org/issue35247
+  # test_tk: tkinter.test.test_tkinter.test_colorchooser.DefaultRootTest hangs
+
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Check Failed! \E[0m"
+    exit 1
+  )
+
+  LD_LIBRARY_PATH="${srcdir:?}/Python-${pkgver}":${LD_LIBRARY_PATH} \
+    LC_CTYPE=en_US.UTF-8 \
+    "${srcdir:?}/Python-${pkgver}/python" -m test.regrtest -v -uall -x test_socket -x test_tk -x test_zlib
+
+}
+
+package_python+clang() {
+
+  optdepends=(
+    'python-setuptools'
+    'python-pip'
+    'sqlite'
+    'mpdecimal: for decimal'
+    'xz: for lzma'
+    'tk: for tkinter'
+  )
+  provides=('python3' 'python' "python=${pkgver}")
+  conflicts=('python')
+  replaces=('python3')
+
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Prepare python Failed! \E[0m"
+    exit 1
+  )
+
+  make DESTDIR="${pkgdir:?}" EXTRA_CFLAGS="${CFLAGS}" install
 
   # Split tests
-  rm -r "$pkgdir"/usr/lib/python*/{test,ctypes/test,distutils/tests,idlelib/idle_test,lib2to3/tests,tkinter/test,unittest/test}
+  rm -r "${pkgdir:?}/usr/lib/python${_pybasever}/"{test,ctypes/test,distutils/tests,idlelib/idle_test,lib2to3/tests,sqlite3/test,tkinter/test,unittest/test}
 
-  # Avoid conflicts with the main 'python' package.
-  rm -f "${pkgdir}/usr/lib/libpython${_pymajver}.so"
-  rm -f "${pkgdir}/usr/share/man/man1/python${_pymajver}.1"
+  # Why are these not done by default...
+  ln -s python3 "${pkgdir:?}/usr/bin/python"
+  ln -s python3-config "${pkgdir:?}/usr/bin/python-config"
+  ln -s idle3 "${pkgdir:?}/usr/bin/idle"
+  ln -s pydoc3 "${pkgdir:?}/usr/bin/pydoc"
+  ln -s "python${_pybasever}.1" "${pkgdir:?}/usr/share/man/man1/python.1"
 
-  # Clean-up reference to build directory
-  sed -i "s|$srcdir/Python-${pkgver}:||" "$pkgdir/usr/lib/python${_pybasever}/config-${_pybasever}-${CARCH}-linux-gnu/Makefile"
-
-  # Add useful scripts FS#46146
-  install -dm755 "${pkgdir}"/usr/lib/python${_pybasever}/Tools/{i18n,scripts}
-  install -m755 Tools/i18n/{msgfmt,pygettext}.py "${pkgdir}"/usr/lib/python${_pybasever}/Tools/i18n/
-  install -m755 Tools/scripts/{README,*py} "${pkgdir}"/usr/lib/python${_pybasever}/Tools/scripts/
+  # some useful "stuff" FS#46146
+  install -dm755 "${pkgdir:?}/usr/lib/python${_pybasever}/Tools/"{i18n,scripts}
+  install -m755 Tools/i18n/{msgfmt,pygettext}.py "${pkgdir:?}/usr/lib/python${_pybasever}/Tools/i18n/"
+  install -m755 Tools/scripts/{README,*py} "${pkgdir:?}/usr/lib/python${_pybasever}/Tools/scripts/"
 
   # License
-  install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  install -Dm644 LICENSE "${pkgdir:?}/usr/share/licenses/python/LICENSE"
+
+}
+
+package_python-tests+clang() {
+
+  pkgdesc="Regression tests packages for Python"
+  depends=('python')
+
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Package python-tests Failed! \E[0m"
+    exit 1
+  )
+
+  make DESTDIR="${pkgdir:?}" EXTRA_CFLAGS="${CFLAGS}" libinstall
+
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/" &&
+    rm -r !(test|ctypes|distutils|idlelib|lib2to3|sqlite3|tkinter|unittest)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/ctypes" &&
+    rm -r !(test)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/distutils" &&
+    rm -r !(tests)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/idlelib" &&
+    rm -r !(idle_test)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/lib2to3" &&
+    rm -r !(tests)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/sqlite3" &&
+    rm -r !(test)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/tkinter" &&
+    rm -r !(test)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/unittest" &&
+    rm -r !(test)
+
 }
