test

diff --git a/python/PKGBUILD b/python/PKGBUILD
--- a/python/PKGBUILD
+++ b/python/PKGBUILD
@@ -1,20 +1,3 @@
-export CC=clang
-export CXX=clang++
-export AR=llvm-ar
-export AS=llvm-as
-export NM=llvm-nm
-export STRIP=llvm-strip
-export OBJCOPY=llvm-objcopy
-export OBJDUMP=llvm-objdump
-export READELF=llvm-readelf
-export HOSTCC=clang
-export HOSTCXX=clang++
-export HOSTAR=llvm-ar
-export LD=ld.lld
-export CC_LD=lld
-export CXX_LD=lld
-export HOSTLD=ld.lld
-
 shopt -s extglob
 
 pkgbase=python
@@ -27,16 +10,24 @@ arch=('x86_64')
 license=('custom')
 url="https://www.python.org/"
 depends=('bzip2' 'expat' 'gdbm' 'libffi' 'libnsl' 'libxcrypt' 'openssl' 'zlib')
-makedepends=('tk' 'sqlite' 'bluez-libs' 'mpdecimal' 'llvm-all' 'gdb' 'xorg-server-xvfb' 'ttf-font')
+makedepends=('tk' 'sqlite' 'bluez-libs' 'mpdecimal' 'llvm' 'gdb' 'ttf-font')
 source=("https://www.python.org/ftp/python/${pkgver%rc*}/Python-${pkgver}.tar.xz"{,.asc})
-sha512sums=('5020407798ebaae6002b8de29475c1064a32f1527a0e4ec6fe7fcf076b4ea3ef0ab4b4a7864a6081cc8dd01dd545123198b11cc8dd1259c670394b7d81f35a86'
-            'SKIP')
-validpgpkeys=('0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D'  # Ned Deily (Python release signing key) <nad@python.org>
-              'E3FF2839C048B25C084DEBE9B26995E310250568'  # Łukasz Langa (GPG langa.pl) <lukasz@langa.pl>
-              'A035C8C19219BA821ECEA86B64E628F8D684696D') # Pablo Galindo Salgado <pablogsal@gmail.com>
+sha256sums=('596c72de998dc39205bc4f70ef0dbf7edec740a306d09b49a9bd0a77806730dc'
+  'SKIP')
+validpgpkeys=(
+  '0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D' # Ned Deily (Python release signing key) <nad@python.org>
+  'E3FF2839C048B25C084DEBE9B26995E310250568' # Łukasz Langa (GPG langa.pl) <lukasz@langa.pl>
+  'A035C8C19219BA821ECEA86B64E628F8D684696D' # Pablo Galindo Salgado <pablogsal@gmail.com>
+)
+
+_llvm=0
 
 prepare() {
-  cd Python-${pkgver}
+
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Prepare Failed! \E[0m"
+    exit 1
+  )
 
   # FS#23997
   sed -i -e "s|^#.* /usr/local/bin/python|#!/usr/bin/python|" Lib/cgi.py
@@ -46,15 +37,22 @@ prepare() {
   rm -r Modules/expat
   rm -r Modules/_ctypes/{darwin,libffi}*
   rm -r Modules/_decimal/libmpdec
+
+  if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]" && ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+    _llvm=1
+  fi
+
 }
 
 build() {
-  cd Python-${pkgver}
 
-  # PGO should be done with -O3
-  # CFLAGS="${CFLAGS/-O2/-O3} -Qunused-arguments -mllvm -polly -mllvm -polly-vectorizer=stripmine"
-  # CFLAGS="${CFLAGS/-march=x86-64/-march=x86-64-v2}"
-  # LDFLAGS="${LDFLAGS} -fuse-ld=lld"
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Build Failed! \E[0m"
+    exit 1
+  )
+  CFLAGS="${CFLAGS}/02/03"
+  LDFLAGS="${LDFLAGS} -fuse-ld=lld"
+
   # Disable bundled pip & setuptools
   ./configure --prefix=/usr \
               --enable-shared \
@@ -69,90 +67,99 @@ build() {
               --enable-loadable-sqlite-extensions \
               --without-ensurepip \
               --with-tzpath=/usr/share/zoneinfo
-              
-  unset CFLAGS
-  # Obtain next free server number for xvfb-run; this even works in a chroot environment.
-  export servernum=99
-  while ! xvfb-run -a -n "$servernum" /bin/true 2>/dev/null; do servernum=$((servernum+1)); done
 
-  LC_CTYPE=en_US.UTF-8 xvfb-run -s "-screen 0 1920x1080x16 -ac +extension GLX" -a -n "$servernum" make EXTRA_CFLAGS="$CFLAGS"
+  unset CFLAGS
+  unset LDFLAGS
+
+  LC_CTYPE=en_US.UTF-8 make regen-all EXTRA_CFLAGS="${CFLAGS}"
+  LC_CTYPE=en_US.UTF-8 make EXTRA_CFLAGS="${CFLAGS}"
+
 }
 
 check() {
+
   # test_socket: test.test_socket.RDSTest.testPeek hangs https://bugs.python.org/issue35247
   # test_tk: tkinter.test.test_tkinter.test_colorchooser.DefaultRootTest hangs
 
-  cd Python-${pkgver}
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Check Failed! \E[0m"
+    exit 1
+  )
 
-  # Obtain next free server number for xvfb-run; this even works in a chroot environment.
-  export servernum=99
-  while ! xvfb-run -a -n "$servernum" /bin/true 2>/dev/null; do servernum=$((servernum+1)); done
+  LD_LIBRARY_PATH="${srcdir:?}/Python-${pkgver}":${LD_LIBRARY_PATH} \
+    LC_CTYPE=en_US.UTF-8 \
+    "${srcdir:?}/Python-${pkgver}/python" -m test.regrtest -v -uall -x test_socket -x test_tk -x test_zlib
 
-  LD_LIBRARY_PATH="${srcdir}/Python-${pkgver}":${LD_LIBRARY_PATH} \
-  LC_CTYPE=en_US.UTF-8 xvfb-run -s "-screen 0 1920x1080x16 -ac +extension GLX" -a -n "$servernum" \
-    "${srcdir}/Python-${pkgver}/python" -m test.regrtest -v -uall -x test_socket -x test_tk
 }
 
 package_python() {
-  optdepends=('python-setuptools'
-              'python-pip'
-              'sqlite'
-              'mpdecimal: for decimal'
-              'xz: for lzma'
-              'tk: for tkinter')
-  provides=('python3')
+
+  optdepends=(
+    'python-setuptools'
+    'python-pip'
+    'sqlite'
+    'mpdecimal: for decimal'
+    'xz: for lzma'
+    'tk: for tkinter'
+  )
+  provides=('python3' 'python' "python=${pkgver}")
+  conflicts=('python')
   replaces=('python3')
 
-  cd Python-${pkgver}
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Prepare python Failed! \E[0m"
+    exit 1
+  )
 
-  # Hack to avoid building again
-  sed -i 's/^all:.*$/all: build_all/' Makefile
-
-  # PGO should be done with -O3
-  CFLAGS="${CFLAGS/-O2/-O3}"
-
-  make DESTDIR="${pkgdir}" EXTRA_CFLAGS="$CFLAGS" install
+  make DESTDIR="${pkgdir:?}" EXTRA_CFLAGS="${CFLAGS}" install
 
   # Split tests
-  rm -r "$pkgdir"/usr/lib/python*/{test,ctypes/test,distutils/tests,idlelib/idle_test,lib2to3/tests,sqlite3/test,tkinter/test,unittest/test}
+  rm -r "${pkgdir:?}/usr/lib/python${_pybasever}/"{test,ctypes/test,distutils/tests,idlelib/idle_test,lib2to3/tests,sqlite3/test,tkinter/test,unittest/test}
 
   # Why are these not done by default...
-  ln -s python3               "${pkgdir}"/usr/bin/python
-  ln -s python3-config        "${pkgdir}"/usr/bin/python-config
-  ln -s idle3                 "${pkgdir}"/usr/bin/idle
-  ln -s pydoc3                "${pkgdir}"/usr/bin/pydoc
-  ln -s python${_pybasever}.1 "${pkgdir}"/usr/share/man/man1/python.1
+  ln -s python3 "${pkgdir:?}/usr/bin/python"
+  ln -s python3-config "${pkgdir:?}/usr/bin/python-config"
+  ln -s idle3 "${pkgdir:?}/usr/bin/idle"
+  ln -s pydoc3 "${pkgdir:?}/usr/bin/pydoc"
+  ln -s "python${_pybasever}.1" "${pkgdir:?}/usr/share/man/man1/python.1"
 
   # some useful "stuff" FS#46146
-  install -dm755 "${pkgdir}"/usr/lib/python${_pybasever}/Tools/{i18n,scripts}
-  install -m755 Tools/i18n/{msgfmt,pygettext}.py "${pkgdir}"/usr/lib/python${_pybasever}/Tools/i18n/
-  install -m755 Tools/scripts/{README,*py} "${pkgdir}"/usr/lib/python${_pybasever}/Tools/scripts/
+  install -dm755 "${pkgdir:?}/usr/lib/python${_pybasever}/Tools/"{i18n,scripts}
+  install -m755 Tools/i18n/{msgfmt,pygettext}.py "${pkgdir:?}/usr/lib/python${_pybasever}/Tools/i18n/"
+  install -m755 Tools/scripts/{README,*py} "${pkgdir:?}/usr/lib/python${_pybasever}/Tools/scripts/"
 
   # License
-  install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  install -Dm644 LICENSE "${pkgdir:?}/usr/share/licenses/python/LICENSE"
+
 }
 
 package_python-tests() {
+
   pkgdesc="Regression tests packages for Python"
   depends=('python')
 
-  cd Python-${pkgver}
+  cd "${srcdir:?}/Python-${pkgver}" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/Python-${pkgver} directory! Package python-tests Failed! \E[0m"
+    exit 1
+  )
 
-  make DESTDIR="${pkgdir}" EXTRA_CFLAGS="$CFLAGS" libinstall
-  cd "$pkgdir"/usr/lib/python*/
-  rm -r !(test|ctypes|distutils|idlelib|lib2to3|sqlite3|tkinter|unittest)
-  cd "$pkgdir"/usr/lib/python*/ctypes
-  rm -r !(test)
-  cd "$pkgdir"/usr/lib/python*/distutils
-  rm -r !(tests)
-  cd "$pkgdir"/usr/lib/python*/idlelib
-  rm -r !(idle_test)
-  cd "$pkgdir"/usr/lib/python*/lib2to3
-  rm -r !(tests)
-  cd "$pkgdir"/usr/lib/python*/sqlite3
-  rm -r !(test)
-  cd "$pkgdir"/usr/lib/python*/tkinter
-  rm -r !(test)
-  cd "$pkgdir"/usr/lib/python*/unittest
-  rm -r !(test)
+  make DESTDIR="${pkgdir:?}" EXTRA_CFLAGS="${CFLAGS}" libinstall
+
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/" &&
+    rm -r !(test|ctypes|distutils|idlelib|lib2to3|sqlite3|tkinter|unittest)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/ctypes" &&
+    rm -r !(test)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/distutils" &&
+    rm -r !(tests)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/idlelib" &&
+    rm -r !(idle_test)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/lib2to3" &&
+    rm -r !(tests)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/sqlite3" &&
+    rm -r !(test)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/tkinter" &&
+    rm -r !(test)
+  cd "${pkgdir:?}/usr/lib/python${_pybasever}/unittest" &&
+    rm -r !(test)
+
 }
